### ISSUE TITLE
Undefined function or variable 'chebfun'. Error Message

### ISSUE THREAD

**Issue by OBigVee** [chebfun/examples#63]
i got 

> **Undefined function or variable 'chebfun'.** Error Message.

`line 26`
`dom = [-1 1 -1 1]; x = chebfun('x',dom(1:2)); tspan = [0 3500];`

it seems he defined a function named `chebfun` somewhere but having read through your code, i can't find the function `chebfun`.
am i missing anything?

**Comment by nickhale** [comment]
Chebfun is not included in MATLAB by default. You can download it (for free) from [this Github repo](https://github.com/chebfun/chebfun) or by following the instructions [here](https://www.chebfun.org/download/).

If you have already downloaded it, then it looks like it was not added to the MATLAB search path. You can find instructions on how to do that [here](https://www.chebfun.org/download/) and [here](https://www.mathworks.com/help/matlab/matlab_env/add-remove-or-reorder-folders-on-the-search-path.html).

**Comment by OBigVee** [comment]
thanks @nickhale, I have been able to figure it out following the instructions in the links you provided.
